# Exercice - Entity 3 - Part 2
entity_items_index:
  methods: GET
  path: /entity3/items/index
  controller: App\Controller\ExoEntity3\ItemsController::index

# Exercice - Entity 3 - Part 1
entity_items_create:
  methods: GET
  path: /entity3/items/create
  controller: App\Controller\ExoEntity3\ItemsController::create

# Exercice - Entity 3 - Part 1
entity_items_store:
  methods: POST
  path: /entity3/items/store
  controller: App\Controller\ExoEntity3\ItemsController::store

# Exercice - Entity 3 - Part 2
entity_items_show:
  methods: GET
  path: /entity3/items/show/{id}
  controller: App\Controller\ExoEntity3\ItemsController::show

# Exercice - Entity 3 - Part 2
entity_items_edit:
  methods: GET
  path: /entity3/items/edit/{id}
  controller: App\Controller\ExoEntity3\ItemsController::edit

# Exercice - Entity 3 - Part 2
entity_items_update:
  methods: POST
  path: /entity3/items/update/{id}
  controller: App\Controller\ExoEntity3\ItemsController::update
